esdata:
    image: ubuntu
    command: true
    volumes:
        - /es/data
        - /log

influxdata:
    image: ubuntu
    command: true
    volumes:
        - /data

rabbitdata:
    image: ubuntu
    command: true
    volumes:
        - /data/log
        - /data/mnesia

rabbitmq:
    image: dockerfile/rabbitmq
    hostname: rabbitmq
    expose:
        - "5672"
        - "15672"

    volumes_from:
        - rabbitdata

mongodb:
    image: dockerfile/mongodb
    expose:
        - "27017"

elasticsearch:
    image: dockerfile/elasticsearch
    hostname: elasticsearch
    command: /elasticsearch/bin/elasticsearch -Des.config=/config/elasticsearch.yml
    expose:
        - "9200"
        - "9300"

    volumes:
        - ./config:/config

    volumes_from:
        - esdata

influxdb:
    image: tutum/influxdb
    hostname: influx
    expose:
        - "8083"
        - "8086"

    volumes_from:
        - influxdata

web:
    build: .
    command: gunicorn -c /config/gunicorn.conf wsgi:app --reload
    volumes:
        - .:/app
        - ./config:/config
    links:
        - mongodb:mongo
        - elasticsearch:es
        - influxdb:influx
        - rabbitmq:mq
    ports:
        - "8000:8000"
        - "8080:8080"
    environment:
        SERVER_NAME: entropealabs.dev
        FACEBOOK_APP_ID: asdasdasdas
        FACEBOOK_APP_SECRET: dsfsdfsdfsdf
